### ISSUE TITLE
could you make a profile for ElCapitan_10.11.4

### ISSUE THREAD

**Issue by matrixorz** [volatilityfoundation/profiles#17]
how to make own profile?if response very thanks

**Comment by kboratynski** [comment]
@matrixorz What is the issue, you have? Please describe your problems.

**Comment by williamshowalter** [comment]
The profile generation "as is" is currently broken for El Capitan (some of the guarantees about declarations in the pre-elcapitan kernel symbols are no longer valid) . The 10.11 profiles up to 10.11.3 had to be made with a modified script by @atcuno and then manually modified by hand to fix additional errors. I'm currently working on seeing if I can fix the profile generation script in the main repo and submit a pull request with a 10.11.4 profile once I have it working. I think I have it where @atcuno did for the 10.11.3 profile, but I'm looking to solve the issue that I patched by hand last time.

**Comment by hexadite-dima** [comment]
@williamshowalter, can you document the manual profile generation procedure, please? I'm having difficulty with 10.11.5 against multiple live memory acquisition tools and I'd like to generate a fresh profile, to pin down the problem.

**Comment by kboratynski** [comment]
@hexadite-dima Have a look at the following webpage: https://github.com/volatilityfoundation/volatility/wiki/Mac#creating-a-profile
