### ISSUE TITLE
How to make a profile for CentOs6.6

### ISSUE THREAD

**Issue by JackNine** [volatilityfoundation/profiles#25]
Hi, I have made many profiles for Ubuntu, but I can not make a profile for Centos. So could anyone tell me the way to make a profile for CentOs6.6?

**Comment by RATBORG** [comment]
Could be done with libdwarf from Fedora and ELF utilities afaik.

**Comment by JackNine** [comment]
I download the source code from "http://pkgs.fedoraproject.org/repo/pkgs/libdwarf/", and I have tried many ways to extract it. Then error comes.....
gzip: stdin: not in gzip format
/bin/gtar: Child returned status 1
/bin/gtar: Error is not recoverable: exiting now

**Comment by d4rkw1ll0w** [comment]
I created a virtual for CentOS version I needed, then installed the kernel-devel tools, libelf, linux-headers, and gcc. May have been a few other packages as well, just keep doing yum install until all the correct packages are installed. Then install git, and clone the volatility repo. Last, run make in the volatility/trunk/tools/linux directory. You wind up with a module.dwarf file, then zip that up along with your System map from /boot/(version)/System.map file and now you have your profile.

**Comment by d4rkw1ll0w** [comment]
https://d4rkw1ll0w4n6.wordpress.com/2018/04/27/creating-volatility-profile-for-centos67/

I wrote up my process for creating CentOS profiles, mine was version 6.7 but these steps will help you create one for 6.6

**Comment by JackNine** [comment]
thx
