### ISSUE TITLE
Probleam With Linux prebuilt Profile

### ISSUE THREAD

**Issue by AnkitKundariya** [volatilityfoundation/profiles#41]
hello everyone ,
    friends I'm facing one problem with volatility version 2.6 can you people please help me.
        problem is : volatility come with default windows profiles but there is no any Linux profile to resolve this problem there is a already some prebuilt Linux profile is available https://github.com/volatilityfoundation/profiles i follow this instructions but still i'm not geting profile in output profile list after performing 

> "python vol.py image info -f /dump/victoria-v8.memdump.img"

    i follow this solution but it's not work for me in volatility version 2.6

**Comment by gleeda** [comment]
That is because the `imageinfo` plugin doesn't work on Linux memory samples.  Do you get any output with `linux_pslist`  or any of the other Linux plugins?  https://github.com/volatilityfoundation/volatility/wiki/Linux%20Command%20Reference

**Comment by AnkitKundariya** [comment]
@gleeda as you mention in above comment **imageinfo**  command doesn't work on Linux memory samples right, now consider a scenario where i have number of Linux profiles and i don't know which profile is idle for my dumps , for this either i have to first find suggested profile by using imageinfo command which help me to go ahead and perform other operations on my Linux memory samples, or another way is to take one by one every profile and test all the profile with my  Linux memory samples. which takes to much time so what I'm asking is, is there any **alternative** command of **imageinfo** which gives me a suggested profile for my  Linux memory samples.
