### ISSUE TITLE
Is it truly possible to use Volatility with Linux memory dumps?

### ISSUE THREAD

**Issue by cpuu** [volatilityfoundation/profiles#46]
(I'm sorry I can not write English well)

Have you guys ever used Volatility Framework with Linux memory dumps, of recent day ?

I have been working hard for a few days. 

I think that Volatility is the de facto standard in window analysis, on the other hands, it does not work with Memdump from Linux.

Recent kernel versions appear to have broken compatibility. Even if you use some profiles provided by [official github](https://github.com/volatilityfoundation/profiles/), it doesn't match even if one number is different by 3 decimal points.

I Used LiME and lmg(linux memory grabber) for creating profile and dumping physical memory.
Everything is OK.

but, Volatility cannot parse the data.
I tried CentOS, Ubuntu, Kali Linux, Debian, Fedora .. and so on and so forth.

Every case, this messages shown

---------- -------------------- --------------- --------------- --------------- ------ ---------- ----------
No suitable address space mapping found
Tried to open image as:
 MachOAddressSpace: mac: need base
 LimeAddressSpace: lime: need base
 WindowsHiberFileSpace32: No base Address Space
 WindowsCrashDumpSpace64BitMap: No base Address Space
 WindowsCrashDumpSpace64: No base Address Space
 HPAKAddressSpace: No base Address Space
 VMWareMetaAddressSpace: No base Address Space
 VirtualBoxCoreDumpElf64: No base Address Space
 VMWareAddressSpace: No base Address Space
 QemuCoreDumpElf: No base Address Space
 WindowsCrashDumpSpace32: No base Address Space
 Win10AMD64PagedMemory: No base Address Space
 WindowsAMD64PagedMemory: No base Address Space
 LinuxAMD64PagedMemory: No base Address Space
 AMD64PagedMemory: No base Address Space
 IA32PagedMemoryPae: No base Address Space
 IA32PagedMemory: No base Address Space
 OSXPmemELF: No base Address Space
 MachOAddressSpace: MachO Header signature invalid
 MachOAddressSpace: MachO Header signature invalid
 LimeAddressSpace: Invalid Lime header signature
 WindowsHiberFileSpace32: PO_MEMORY_IMAGE is not available in profile
 WindowsCrashDumpSpace64BitMap: Header signature invalid
 WindowsCrashDumpSpace64: Header signature invalid
 HPAKAddressSpace: Invalid magic found
 VMWareMetaAddressSpace: VMware metadata file is not available
 VirtualBoxCoreDumpElf64: ELF Header signature invalid
 VMWareAddressSpace: Invalid VMware signature: 0xee300
 QemuCoreDumpElf: ELF Header signature invalid
 WindowsCrashDumpSpace32: Header signature invalid
 Win10AMD64PagedMemory: Incompatible profile Linuxcpuu-VirtualBox-2017-05-01_04_31_48-profilex86 selected
 WindowsAMD64PagedMemory: Incompatible profile Linuxcpuu-VirtualBox-2017-05-01_04_31_48-profilex86 selected
 LinuxAMD64PagedMemory: Incompatible profile Linuxcpuu-VirtualBox-2017-05-01_04_31_48-profilex86 selected
 AMD64PagedMemory: Incompatible profile Linuxcpuu-VirtualBox-2017-05-01_04_31_48-profilex86 selected
 IA32PagedMemoryPae: Failed valid Address Space check
 IA32PagedMemory: Failed valid Address Space check
 OSXPmemELF: ELF Header signature invalid
 FileAddressSpace: Must be first Address Space
 ArmAddressSpace: Failed valid Address Space check

—
Was there a mistake in my work? Or does the volatility still not support those versions of Linux?

**Comment by deeso** [comment]
What command are you using and are the profies in your path?  Does
volatility see the profiles in your path?

**Comment by cpuu** [comment]
sure, of course, I tried hundreds of times, with tens of kernels(Ubuntu, CentOS, Fedora.. )

volatility 2.6
osboxes@osboxes:~/volatility$ python vol.py --info
Volatility Foundation Volatility Framework 2.6


Profiles
--------
LinuxKali-Linux-2017x64                             - A Profile for Linux Kali-Linux-2017 x64
LinuxMyUbuntu1604x64                                - A Profile for Linux MyUbuntu1604 x64
LinuxUbuntu16041x64                                 - A Profile for Linux Ubuntu16041 x64
LinuxUbuntu1604x64                                  - A Profile for Linux Ubuntu1604 x64
Linuxcpuu-VirtualBox-2017-05-01_04_31_48-profilex86 - A Profile for Linux cpuu-VirtualBox-2017-05-01_04.31.48-profile x86
Linuxosboxes-2017-05-01_07_01_18-profilex86         - A Profile for Linux osboxes-2017-05-01_07.01.18-profile x86
Linuxosboxes-2017-05-01_21_43_17-profilex64         - A Profile for Linux osboxes-2017-05-01_21.43.17-profile x64
Linuxsiftworkstation-2017-05-01_10_06_25-profilex64 - A Profile for Linux siftworkstation-2017-05-01_10.06.25-profile x64


Alright ..

I used linux_pslist , linux_psaux and so on. none of them effect.

Does it cause VirtualBox? why it not works?

**Comment by deeso** [comment]
When you execute the volatility command, do you specify the profile for the
memory image?

**Comment by cpuu** [comment]
sure, of course.. I am not newbie.. I am doing well on Windows.. but why it not show the results only in Linux.. I don't know what to do

**Comment by deeso** [comment]
I meant to ask for the specific command you are running.  I am trying to set context and identify the root cause of the problem.  Can you share the exact command you are running?

**Comment by cpuu** [comment]
Normal case :
sudo python vol.py -f  ../Desktop/osboxes-2017-05-01_07.01.18-memory.lime  --profile=Linuxosboxes-2017-05-01_07_01_18-profilex86 linux_pslist

When I use [lmg](https://github.com/halpomeranz/lmg) style : 
sudo python vol.py --conf-file=../capture/osboxes-2017-05-01_21.43.17/volatilityrc  linux_bash | head

in volatilityrc file : 
`cpuu@osboxes:/media/cpuu/LinuxMemoryGrab/lmg/capture/osboxes-2017-05-01_21.43.17$ cat volatilityrc 
[DEFAULT]
PLUGINS=/media/cpuu/LinuxMemoryGrab/lmg/capture/osboxes-2017-05-01_21.43.17
PROFILE=Linuxosboxes-2017-05-01_21_43_17-profilex64
LOCATION=file:////media/cpuu/LinuxMemoryGrab/lmg/capture/osboxes-2017-05-01_21.43.17/osboxes-2017-05-01_21.43.17-memory.lime`

**Comment by deeso** [comment]
Ok.  Could it be an issue with lime?  Have you tried loading a memory snap
shot from Vbox?

**Comment by cpuu** [comment]
Oh I have not heard about that. I will search that way and try it/

**Comment by atcuno** [comment]
Can you list uname -a for the system where you ran lmg? Also, what is
the distro? And is this a virtual machine or a physical system?

Thanks,
Andrew (@attrc)

**Comment by cpuu** [comment]
I tried Ubuntu, Fedora, CentOS and so on. 

especially, choose one distro, Ubuntu 16.04.1 

uname -a
Linux osboxes 4.8.0-49-generic #52~16.04.1-Ubuntu SMP Thu Apr 20 10:55:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
This is virtualbox for windows version 5.0.26 r108824

When I did it on the real Linux machine .
Linux sep_gpu1 4.2.0-38-generic #45~14.04.1-Ubuntu SMP Thu Jun 9 09:27:51 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Both cases do not work.

**Comment by cpuu** [comment]
I did with VMware Workstation (not Virtual Box) 
on the 4.4.0-31-generic Ubuntu 14.04 

python vol.py  --conf-file=../capture/ubuntu-2017-05-02_08.36.09/volatilityrc  linux_pslist
Volatility Foundation Volatility Framework 2.6
Offset             Name                 Pid             PPid            Uid             Gid    DTB                Start Time
------------------ -------------------- --------------- --------------- --------------- ------ ------------------ ----------
0xffff88003cc60000 init                 1               0               0               0      0x000000003cac1000 2017-05-02 15:27:55 UTC+0000
0xffff88003cc60dc0 kthreadd             2               0               0               0      ------------------ 2017-05-02 15:27:55 UTC+0000
0xffff88003cc61b80 ksoftirqd/0          3               2               0               0      ------------------ 2017-05-02 15:27:55 UTC+0000
0xffff88003cc62940 kworker/0:0          4               2               0               0      ------------------ 2017-05-02 15:27:55 UTC+0000
0xffff88003cc63700 kworker/0:0H         5               2               0               0      ------------------ 2017-05-02 15:27:55 

it works!!! oh shit... My effort was wasted... 
is it virtual box flaw ? i have no idea. but i did!!

**Comment by deeso** [comment]
I have used Linux KVM in the past without any issues..

**Comment by bneuburg** [comment]
If you are using LiME to acquire memory try passing the `timeout=0` module parameter when modprobing. This bit me a few times when trying to dump the memory from a KVM virtual machine. It's possible that VirtualBox is too slow in returning some of the memory pages and in this case LiME will just write zeroes instead of waiting.
